-- Generated by npm run sync:design. Do not edit by hand.
WFRP_THEME = {
  canvas = { 0.0392, 0.0549, 0.0824, 1 },
  frame = { 0.0471, 0.0706, 0.1137, 1 },
  surface = { 0.0627, 0.0902, 0.1333, 1 },
  elevated = { 0.0902, 0.1333, 0.2, 1 },
  raised = { 0.1137, 0.1647, 0.2392, 1 },
  line = { 0.2078, 0.2588, 0.3412, 1 },
  lineSoft = { 0.1255, 0.1725, 0.2314, 1 },
  text = { 0.9098, 0.9294, 0.9686, 1 },
  muted = { 0.6039, 0.6588, 0.7333, 1 },
  gold = { 0.9137, 0.6784, 0.2314, 1 },
  goldBright = { 0.9569, 0.7882, 0.3647, 1 },
  goldDark = { 0.502, 0.3804, 0.1059, 1 },
  blue = { 0.2941, 0.6078, 1, 1 },
  green = { 0.3098, 0.7882, 0.4824, 1 },
  red = { 0.9451, 0.4157, 0.4157, 1 },
  warning = { 0.8431, 0.6157, 0.3098, 1 },
}
WFRP_DIMENSIONS = {
  frameWidth = 760, frameHeight = 520, sidebarWidth = 116,
  tabHeight = 38, buttonHeight = 30, metricHeight = 60,
  hudWidth = 344, hudHeight = 58,
}
