name = "wow-forever-route-planner"
compatibility_date = "2026-10-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "WFRP_DB"
database_name = "oip-agent-db"
database_id = "6be1bb1c-c9ad-4b59-9c91-9612266f1bd7"
